### ISSUE TITLE
Any updates coming?

### ISSUE THREAD

**Issue by Ilyes512** [gmanricks/Stagr#11]
Hey,
Wanted to ask you for a update? It's been 8 months since last commit. It's because of Stagr I finnally trieed vagrent :+1:

**Comment by simondavies** [comment]
what your looking to do if you need it updated?  I just used it , i had to update the vagrant file a little to work with the latest vagrant version etc but thats can alos bee seen on his other branch, let us know what your issue is if any.

**Comment by Ilyes512** [comment]
Everything did work fine (just the warnings I believe about using the first API).

Just thought that the there might be some new updates to the repo that weren't pushed yet or something like that. "Check back for updates, big things are coming." > 8 month's ago. Just learned about Vagrant then and I was really excited (real geeky ghehe :P).

I will try the refactored one and once I learn more about vagrant (meaning Puppet. Vagrant is so easy!) and I see possible fixes/updates I will make a PR :)

**Comment by simondavies** [comment]
im the same as you tried puphpet but its not up to date and some one on the laravel forum pointed me to this, seems to be working just been adding updating the vagrant file to accommodate the latest versions all seems fine just the vhost to the domain name locally not playing ball just yet but ip is fine.  thanks
